name: Build and publish EPG

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install requests lxml

      - name: EPG herunterladen
        run: |
          mkdir -p public
          python3 <<'PYCODE'
          import requests, gzip, shutil

          URL = "https://epgshare01.online/epgshare01/epg_rip.xml.gz"
          print(f"Fetching {URL}")
          r = requests.get(URL, timeout=300, headers={"User-Agent": "Mozilla/5.0"})
          r.raise_for_status()
          with open('public/full_epg.xml.gz','wb') as f:
              f.write(r.content)
          print("Downloaded", len(r.content), "bytes")
          PYCODE

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
