name: Build and publish EPG via Schedules Direct

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Dependencies installieren
        run: |
          pip install requests lxml

      - name: Schedules Direct Grabber installieren
        run: |
          pip install sdjson

      - name: EPG von Schedules Direct laden
        env:
          SD_USERNAME: ${{ secrets.SD_USERNAME }}
          SD_PASSWORD: ${{ secrets.SD_PASSWORD }}
        run: |
          mkdir -p public
          # Login und Konfiguration
          sdjson config --username "$SD_USERNAME" --password "$SD_PASSWORD"
          # EPG-Daten ziehen (Standard: 7 Tage)
          sdjson lineup add DE
          sdjson lineup add AT
          sdjson lineup add CH
          sdjson lineup add IT
          sdjson download
          # Aus JSON eine XMLTV-Datei erzeugen
          sdjson export xmltv > public/full_epg.xml
          # Komprimieren
          gzip -f public/full_epg.xml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
